'use client';

import { useEffect, useMemo, useState } from 'react';
import Editor from '@monaco-editor/react';
type Problem = { id: string; title: string; topic: string; languages: string[]; completed?: string[] };
type Detail = Problem & { description: string; code: Record<string,string>; tests: Record<string,string> };
const fallback: Detail = { id:'arrays-hashing/contains-duplicate', title:'Contains Duplicate', topic:'Arrays & Hashing', languages:['typescript','python'], description:'Given an integer array nums, return true if any value appears at least twice. Return false when every element is distinct.', code:{typescript:'export function containsDuplicate(nums: number[]): boolean {\n  const seen = new Set<number>();\n\n  for (const num of nums) {\n    // Try a breakpoint here\n    if (seen.has(num)) return true;\n    seen.add(num);\n  }\n\n  return false;\n}',python:''}, tests:{typescript:'4 local test cases',python:'4 local test cases'} };

export default function Home(){
 const [problems,setProblems]=useState<Problem[]>([fallback]); const [selected,setSelected]=useState<Detail>(fallback); const [language,setLanguage]=useState('typescript'); const [code,setCode]=useState(fallback.code.typescript); const [query,setQuery]=useState(''); const [output,setOutput]=useState('Loading your local exercise…'); const [running,setRunning]=useState(false); const [loaded,setLoaded]=useState(false);
 useEffect(()=>{Promise.all([fetch('http://localhost:4311/api/problems').then(r=>r.json()),fetch(`http://localhost:4311/api/problems/${fallback.id}`).then(r=>r.json())]).then(([items,d])=>{setProblems(items);setSelected(d);setLanguage('typescript');setCode(d.code.typescript??'');setOutput('Ready. Run the tests when you are done.');setLoaded(true)}).catch(()=>setOutput('Runner is offline. Start the app with npm run dev from the web folder.'))},[]);
 async function choose(p:Problem){setLoaded(false);try{const d=await fetch(`http://localhost:4311/api/problems/${p.id}`).then(r=>r.json());setSelected(d);setLanguage(d.languages[0]);setCode(d.code[d.languages[0]]??'');setOutput('Ready.');setLoaded(true)}catch{setSelected({...fallback,...p});setOutput('Could not load this exercise.')}}
 function switchLanguage(next:string){setLanguage(next);setCode(selected.code[next]??'');setOutput('Ready.')}
 async function execute(action:'run'|'debug'|'submit'){setRunning(true);setOutput(action==='submit'?'Checking submission…':action==='debug'?'Running detailed diagnostics…':'Running code…');try{const r=await fetch('http://localhost:4311/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,language,code,action})});const result=await r.json();setOutput(result.output||'No output');if(result.submitted)setProblems(items=>items.map(item=>item.id===selected.id?{...item,completed:[...new Set([...(item.completed??[]),language])]}:item))}catch{setOutput('Runner is offline. Start the app with npm run dev from the web folder.')}finally{setRunning(false)}}
 const visible=useMemo(()=>problems.filter(p=>`${p.title} ${p.topic}`.toLowerCase().includes(query.toLowerCase())),[problems,query]);
 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">N</span><span>local<span className="accent">code</span></span></div><div className="progress"><span>Practice workspace</span><strong>{problems.length} problems</strong></div><span className="local-pill"><i/> Runs on your machine</span></header><section className="workspace">
 <aside className="problem-list"><div className="list-head"><h1>Problems</h1><input aria-label="Search problems" placeholder="Search problems…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="problem-scroll">{visible.map((p,i)=><button className={`problem-row ${p.id===selected.id?'active':''}`} key={p.id} onClick={()=>choose(p)}><span className={`number ${p.completed?.length?'done':''}`}>{p.completed?.length?'✓':String(i+1).padStart(2,'0')}</span><span><b>{p.title}</b><small>{p.topic}</small></span><em>{p.languages.length===2?'PY · TS':p.languages[0]==='python'?'PY':'TS'}</em></button>)}</div></aside>
 <section className="problem-pane"><div className="pane-tabs"><span className="selected">Description</span><span>Tests</span></div><article className="statement"><span className="topic-label">{selected.topic}</span><h2>{selected.title}</h2><div className="difficulty">Practice</div><p>{selected.description}</p><h3>Local test suite</h3><div className="example"><span>Tests</span><code>{selected.tests[language]??'Tests available locally'}</code></div><p className="hint">Your code is saved to the exercise file when you run the tests.</p></article></section>
 <section className="code-pane"><div className="code-head"><div className="language-tabs">{selected.languages.map(lang=><button key={lang} className={lang===language?'active':''} onClick={()=>switchLanguage(lang)}>{lang==='typescript'?'TypeScript':'Python'}</button>)}</div><div className="run-actions"><button className="secondary" onClick={()=>execute('run')} disabled={running||!loaded}>▶ Run</button><button className="secondary" onClick={()=>execute('debug')} disabled={running||!loaded}>◆ Debug</button><button onClick={()=>execute('submit')} disabled={running||!loaded}>{running?'Working…':'Submit'}</button></div></div><div className="editor-wrap"><Editor height="100%" language={language} theme="vs-dark" value={code} onChange={value=>setCode(value??'')} loading={<div className="editor-loading">Loading editor…</div>} options={{fontSize:14,fontFamily:'JetBrains Mono, SFMono-Regular, Consolas, monospace',fontLigatures:true,lineHeight:22,minimap:{enabled:false},scrollBeyondLastLine:false,automaticLayout:true,tabSize:2,insertSpaces:true,wordWrap:'off',padding:{top:16,bottom:16},renderLineHighlight:'line',smoothScrolling:true,bracketPairColorization:{enabled:true},guides:{bracketPairs:true,indentation:true}}}/></div><div className="console"><div className="console-head"><span>Output</span></div><pre>{output}</pre></div></section>
 </section></main>
}
