'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties, PointerEvent as ReactPointerEvent } from 'react';
import Editor from '@monaco-editor/react';
import type { editor as MonacoEditor } from 'monaco-editor';
type Problem = { id: string; title: string; topic: string; languages: string[]; completed?: string[] };
type Detail = Problem & { description: string; code: Record<string,string>; tests: Record<string,string> };
type Review = { summary: string; comments: { line:number; kind:'praise'|'roast'|'tip'; message:string }[] };
const fallback: Detail = { id:'arrays-hashing/contains-duplicate', title:'Contains Duplicate', topic:'Arrays & Hashing', languages:['typescript','python'], description:'Given an integer array nums, return true if any value appears at least twice. Return false when every element is distinct.', code:{typescript:'export function containsDuplicate(nums: number[]): boolean {\n  const seen = new Set<number>();\n\n  for (const num of nums) {\n    // Try a breakpoint here\n    if (seen.has(num)) return true;\n    seen.add(num);\n  }\n\n  return false;\n}',python:''}, tests:{typescript:'4 local test cases',python:'4 local test cases'} };

export default function Home(){
 const [problems,setProblems]=useState<Problem[]>([fallback]); const [selected,setSelected]=useState<Detail>(fallback); const [language,setLanguage]=useState('typescript'); const [code,setCode]=useState(fallback.code.typescript); const [query,setQuery]=useState(''); const [output,setOutput]=useState('Loading your local exercise…'); const [running,setRunning]=useState(false); const [loaded,setLoaded]=useState(false); const [coachOn,setCoachOn]=useState(false); const [voiceOn,setVoiceOn]=useState(false); const [review,setReview]=useState<Review|null>(null); const [reviewing,setReviewing]=useState(false); const [reviewError,setReviewError]=useState(''); const [outputHeight,setOutputHeight]=useState(190); const spokenReview=useRef(''); const editorRef=useRef<MonacoEditor.IStandaloneCodeEditor|null>(null); const zoneIds=useRef<string[]>([]);
 useEffect(()=>{Promise.all([fetch('http://localhost:4311/api/problems').then(r=>r.json()),fetch(`http://localhost:4311/api/problems/${fallback.id}`).then(r=>r.json())]).then(([items,d])=>{setProblems(items);setSelected(d);setLanguage('typescript');setCode(d.code.typescript??'');setOutput('Ready. Run the tests when you are done.');setLoaded(true)}).catch(()=>setOutput('Runner is offline. Start the app with npm run dev from the web folder.'))},[]);
 async function choose(p:Problem){setLoaded(false);try{const d=await fetch(`http://localhost:4311/api/problems/${p.id}`).then(r=>r.json());setSelected(d);setLanguage(d.languages[0]);setCode(d.code[d.languages[0]]??'');setOutput('Ready.');setLoaded(true)}catch{setSelected({...fallback,...p});setOutput('Could not load this exercise.')}}
 function switchLanguage(next:string){setLanguage(next);setCode(selected.code[next]??'');setOutput('Ready.')}
 useEffect(()=>{if(!coachOn||!loaded||!code.trim())return;setReview(null);setReviewing(true);const controller=new AbortController();const timer=setTimeout(async()=>{setReviewError('');try{const response=await fetch('http://localhost:4311/api/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,language,code}),signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error);setReview(result)}catch(error){if((error as Error).name!=='AbortError')setReviewError((error as Error).message)}finally{if(!controller.signal.aborted)setReviewing(false)}},850);return()=>{clearTimeout(timer);controller.abort()}},[code,language,selected.id,coachOn,loaded]);
 useEffect(()=>{if(!coachOn||!voiceOn||!review||typeof speechSynthesis==='undefined')return;const speech=[review.summary,...review.comments.slice(0,3).map(comment=>`Line ${comment.line}. ${comment.message}`)].join(' ');if(!speech||speech===spokenReview.current)return;spokenReview.current=speech;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(speech);utterance.rate=1.08;utterance.pitch=1.08;const voices=speechSynthesis.getVoices();utterance.voice=voices.find(voice=>/Samantha|Ava|Daniel|Google US English/i.test(voice.name))??voices.find(voice=>voice.lang.startsWith('en'))??null;speechSynthesis.speak(utterance);return()=>speechSynthesis.cancel()},[review,coachOn,voiceOn]);
 useEffect(()=>{const instance=editorRef.current;if(!instance)return;instance.changeViewZones(accessor=>{zoneIds.current.forEach(id=>accessor.removeZone(id));zoneIds.current=[];if(!coachOn||!review)return;const lineCount=instance.getModel()?.getLineCount()??0;for(const comment of review.comments.slice(0,10)){if(comment.line<1||comment.line>lineCount)continue;const node=document.createElement('div');node.className=`inline-roast ${comment.kind}`;const label=document.createElement('b');label.textContent=comment.kind==='praise'?'BYTE APPROVES':'BYTE';const message=document.createElement('span');message.textContent=comment.message;node.append(label,message);zoneIds.current.push(accessor.addZone({afterLineNumber:comment.line,heightInLines:2,domNode:node}))}})},[review,coachOn]);
 function beginResize(event:ReactPointerEvent){event.preventDefault();const startY=event.clientY,startHeight=outputHeight;const move=(e:PointerEvent)=>setOutputHeight(Math.max(110,Math.min(window.innerHeight*.55,startHeight-(e.clientY-startY))));const stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop)}
 async function execute(action:'run'|'debug'|'submit'){setRunning(true);setOutput(action==='submit'?'Checking submission…':action==='debug'?'Running script with debug diagnostics…':'Running code…');try{const r=await fetch('http://localhost:4311/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,language,code,action})});const result=await r.json();setOutput(result.output||'Script finished without printing anything. Add console.log(...) or print(...) to inspect values.');if(result.submitted)setProblems(items=>items.map(item=>item.id===selected.id?{...item,completed:[...new Set([...(item.completed??[]),language])]}:item))}catch{setOutput('Runner is offline. Start the app with npm run dev from the web folder.')}finally{setRunning(false)}}
 const visible=useMemo(()=>problems.filter(p=>`${p.title} ${p.topic}`.toLowerCase().includes(query.toLowerCase())),[problems,query]);
 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">N</span><span>local<span className="accent">code</span></span></div><div className="progress"><span>Practice workspace</span><strong>{problems.length} problems</strong></div><span className="local-pill"><i/> Runs on your machine</span></header><section className="workspace">
 <aside className="problem-list"><div className="list-head"><h1>Problems</h1><input aria-label="Search problems" placeholder="Search problems…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="problem-scroll">{visible.map((p,i)=><button className={`problem-row ${p.id===selected.id?'active':''}`} key={p.id} onClick={()=>choose(p)}><span className={`number ${p.completed?.length?'done':''}`}>{p.completed?.length?'✓':String(i+1).padStart(2,'0')}</span><span><b>{p.title}</b><small>{p.topic}</small></span><em>{p.languages.length===2?'PY · TS':p.languages[0]==='python'?'PY':'TS'}</em></button>)}</div></aside>
 <section className="problem-pane"><div className="pane-tabs"><span className="selected">Description</span><span>Tests</span></div><article className="statement"><span className="topic-label">{selected.topic}</span><h2>{selected.title}</h2><div className="difficulty">Practice</div><p>{selected.description}</p><h3>Local test suite</h3><div className="example"><span>Tests</span><code>{selected.tests[language]??'Tests available locally'}</code></div><p className="hint">Your code is saved to the exercise file when you run the tests.</p></article></section>
 <section className="code-pane" style={{'--output-height':`${outputHeight}px`} as CSSProperties}><div className="code-head"><div className="language-tabs">{selected.languages.map(lang=><button key={lang} className={lang===language?'active':''} onClick={()=>switchLanguage(lang)}>{lang==='typescript'?'TypeScript':'Python'}</button>)}</div><div className="run-actions"><button className={`coach-toggle ${coachOn?'on':''}`} onClick={()=>setCoachOn(value=>!value)}>🔥 Byte {coachOn?(reviewing?'watching…':'On'):'Off'}</button>{coachOn&&<button className="voice-toggle" title={voiceOn?'Mute Byte':'Let Byte speak'} onClick={()=>{setVoiceOn(value=>!value);speechSynthesis.cancel()}}>{voiceOn?'🔊':'🔇'}</button>}<button className="secondary" onClick={()=>execute('run')} disabled={running||!loaded}>▶ Run</button><button className="secondary" onClick={()=>execute('debug')} disabled={running||!loaded}>◆ Debug</button><button onClick={()=>execute('submit')} disabled={running||!loaded}>{running?'Working…':'Submit'}</button></div></div><div className="editor-wrap"><Editor height="100%" language={language} theme="vs-dark" value={code} onMount={instance=>{editorRef.current=instance}} onChange={value=>setCode(value??'')} loading={<div className="editor-loading">Loading editor…</div>} options={{fontSize:14,fontFamily:'JetBrains Mono, SFMono-Regular, Consolas, monospace',fontLigatures:true,lineHeight:22,minimap:{enabled:false},scrollBeyondLastLine:false,automaticLayout:true,tabSize:2,insertSpaces:true,wordWrap:'off',padding:{top:16,bottom:16},renderLineHighlight:'line',smoothScrolling:true,bracketPairColorization:{enabled:true},guides:{bracketPairs:true,indentation:true}}}/>{coachOn&&reviewError&&<div className="coach-error">🔥 {reviewError}</div>}</div><div className="resize-handle" role="separator" aria-label="Resize output panel" onPointerDown={beginResize}><span/></div><div className="console"><div className="console-head"><span>Output</span><span className="resize-hint">drag to resize</span></div><div className="lower-panels"><pre>{output}</pre></div></div></section>
 </section></main>
}
